# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    tags:
    - '*'

permissions:
  contents: read

jobs:

  create_release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # To fetch all history and tags

      # Step 2: Get the previous tag (previous release)
      - name: Get previous tag
        id: prev_tag
        run: |
          PREV_TAG=$(git tag --sort=-creatordate | sed -n '2p' || echo "")
          echo "Previous tag: $PREV_TAG"
          echo "PREV_TAG=$PREV_TAG" >> $GITHUB_ENV

      # Step 3: Generate release notes from commits
      - name: Generate release notes
        id: release_notes
        run: |
          REPO_URL="https://github.com/${{ github.repository }}"
          RELEASE_BODY="## What's New in ${{ github.ref_name }}\n\n### Changes:\n"
          
          if [ -z "$PREV_TAG" ]; then
            RELEASE_BODY="🚀 **First Release!**\n\n🎉 Welcome to the first release of the project!"
          else
            # Retrieve the commit hashes as short hashes using --abbrev-commit
            COMMITS=$(git log $PREV_TAG..HEAD --pretty=format:"%h" --reverse)
            for COMMIT in $COMMITS; do
              MESSAGE=$(git log -1 --pretty=format:"%s" $COMMIT)
              COMMIT_URL="$REPO_URL/commit/$COMMIT"
              RELEASE_BODY+=" - 🔹 [$COMMIT]($COMMIT_URL) $MESSAGE\n"
            done
          fi

          echo $RELEASE_BODY > release_notes.txt

      # Step 4: Load release notes into an environment variable
      - name: Load release notes into variable
        id: load_notes
        run: |
          RELEASE_BODY=$(cat release_notes.txt)
          echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
          echo -e "$RELEASE_BODY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # Step 5: Create the release on GitHub
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body: ${{ env.RELEASE_BODY }}  # Use the loaded environment variable with markdown
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  deploy-package:
    needs: create-release
    runs-on: ubuntu-latest
    #needs: tests-before-publish
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          pip install build wheel setuptools
      - name: Build package
        run: python -m build --no-isolation --wheel
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
